# **************************************************************************** #
#                                                                          #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bde-albu <bde-albu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/31 14:10:20 by bde-albu          #+#    #+#              #
#    Updated: 2025/04/04 12:19:52 by bde-albu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CFLAGS = -Wall -Wextra -Werror

CC = gcc

SRC = \
ft_strcpy.c \
ft_lsadd_front.c \
ft_lstlast.c \
ft_atoi.c \
ft_bzero.c \
ft_calloc.c \
ft_isalnum.c \
ft_isalpha.c \
ft_isascii.c \
ft_isdigit.c \
ft_isprint.c \
ft_itoa.c \
ft_memchr.c \
ft_memcmp.c \
ft_memcpy.c \
ft_memmove.c \
ft_memset.c \
ft_putchar_fd.c \
ft_putendl_fd.c \
ft_putnbr_fd.c \
ft_putstr_fd.c \
ft_split.c \
ft_strcat.c \
ft_strchr.c \
ft_strdup.c \
ft_striteri.c \
ft_strjoin.c \
ft_strlcat.c \
ft_strlcpy.c \
ft_strlen.c \
ft_strmapi.c \
ft_strncmp.c \
ft_strnstr.c \
ft_strrchr.c \
ft_strtrim.c \
ft_substr.c \
ft_tolower.c \
ft_toupper.c \
ft_lstclear.c \
ft_lstnew.c \
ft_strncpy.c \
ft_lstdelone.c \
ft_lstsize.c \
ft_realloc.c \
ft_lsadd_back.c \
ft_lstiter.c


OBJ = $(SRC:.c=.o)

$(NAME): $(OBJ)
	ar rcs $(NAME) $(OBJ)

ft_atoi.o: ft_atoi.c
	$(CC) $(CFLAGS) -c ft_atoi.c -o ft_atoi.o

ft_isalpha.o: ft_isalpha.c
	$(CC) $(CFLAGS) -c ft_isalpha.c -o ft_isalpha.o

ft_itoa.o: ft_itoa.c
	$(CC) $(CFLAGS) -c ft_itoa.c -o ft_itoa.o

ft_memmove.o: ft_memmove.c
	$(CC) $(CFLAGS) -c ft_memmove.c -o ft_memmove.o

ft_putnbr_fd.o: ft_putnbr_fd.c
	$(CC) $(CFLAGS) -c ft_putnbr_fd.c -o ft_putnbr_fd.o

ft_strchr.o: ft_strchr.c
	$(CC) $(CFLAGS) -c ft_strchr.c -o ft_strchr.o

ft_strlcat.o: ft_strlcat.c
	$(CC) $(CFLAGS) -c ft_strlcat.c -o ft_strlcat.o

ft_strncmp.o: ft_strncmp.c
	$(CC) $(CFLAGS) -c ft_strncmp.c -o ft_strncmp.o

ft_substr.o: ft_substr.c
	$(CC) $(CFLAGS) -c ft_substr.c -o ft_substr.o

ft_bzero.o: ft_bzero.c
	$(CC) $(CFLAGS) -c ft_bzero.c -o ft_bzero.o

ft_isascii.o: ft_isascii.c
	$(CC) $(CFLAGS) -c ft_isascii.c -o ft_isascii.o

ft_memchr.o: ft_memchr.c
	$(CC) $(CFLAGS) -c ft_memchr.c -o ft_memchr.o

ft_memset.o: ft_memset.c
	$(CC) $(CFLAGS) -c ft_memset.c -o ft_memset.o

ft_putstr_fd.o: ft_putstr_fd.c
	$(CC) $(CFLAGS) -c ft_putstr_fd.c -o ft_putstr_fd.o

ft_strdup.o: ft_strdup.c
	$(CC) $(CFLAGS) -c ft_strdup.c -o ft_strdup.o

ft_strlcpy.o: ft_strlcpy.c
	$(CC) $(CFLAGS) -c ft_strlcpy.c -o ft_strlcpy.o

ft_strnstr.o: ft_strnstr.c
	$(CC) $(CFLAGS) -c ft_strnstr.c -o ft_strnstr.o

ft_tolower.o: ft_tolower.c
	$(CC) $(CFLAGS) -c ft_tolower.c -o ft_tolower.o

ft_calloc.o: ft_calloc.c
	$(CC) $(CFLAGS) -c ft_calloc.c -o ft_calloc.o

ft_isdigit.o: ft_isdigit.c
	$(CC) $(CFLAGS) -c ft_isdigit.c -o ft_isdigit.o

ft_memcmp.o: ft_memcmp.c
	$(CC) $(CFLAGS) -c ft_memcmp.c -o ft_memcmp.o

ft_putchar_fd.o: ft_putchar_fd.c
	$(CC) $(CFLAGS) -c ft_putchar_fd.c -o ft_putchar_fd.o

ft_split.o: ft_split.c
	$(CC) $(CFLAGS) -c ft_split.c -o ft_split.o

ft_striteri.o: ft_striteri.c
	$(CC) $(CFLAGS) -c ft_striteri.c -o ft_striteri.o

ft_strlen.o: ft_strlen.c
	$(CC) $(CFLAGS) -c ft_strlen.c -o ft_strlen.o

ft_strrchr.o: ft_strrchr.c
	$(CC) $(CFLAGS) -c ft_strrchr.c -o ft_strrchr.o

ft_toupper.o: ft_toupper.c
	$(CC) $(CFLAGS) -c ft_toupper.c -o ft_toupper.o

ft_isalnum.o: ft_isalnum.c
	$(CC) $(CFLAGS) -c ft_isalnum.c -o ft_isalnum.o

ft_isprint.o: ft_isprint.c
	$(CC) $(CFLAGS) -c ft_isprint.c -o ft_isprint.o

ft_memcpy.o: ft_memcpy.c
	$(CC) $(CFLAGS) -c ft_memcpy.c -o ft_memcpy.o

ft_putendl_fd.o: ft_putendl_fd.c
	$(CC) $(CFLAGS) -c ft_putendl_fd.c -o ft_putendl_fd.o

ft_strcat.o: ft_strcat.c
	$(CC) $(CFLAGS) -c ft_strcat.c -o ft_strcat.o

ft_strjoin.o: ft_strjoin.c
	$(CC) $(CFLAGS) -c ft_strjoin.c -o ft_strjoin.o

ft_strmapi.o: ft_strmapi.c
	$(CC) $(CFLAGS) -c ft_strmapi.c -o ft_strmapi.o

ft_strtrim.o: ft_strtrim.c
	$(CC) $(CFLAGS) -c ft_strtrim.c -o ft_strtrim.o

ft_realloc.o: ft_realloc.c
	$(CC) $(CFLAGS) -c ft_realloc.c -o ft_realloc.o

ft_strcpy.o: ft_strcpy.c
	$(CC) $(CFLAGS) -c ft_strcpy.c -o ft_strcpy.o

ft_strncpy.o: ft_strncpy.c
	$(CC) $(CFLAGS) -c ft_strncpy.c -o ft_strncpy.o

ft_lstclear.o: ft_lstclear.c
	$(CC) $(CFLAGS) -c ft_lstclear.c -o ft_lstclear.o

ft_lstdelone.o: ft_lstdelone.c
	$(CC) $(CFLAGS) -c ft_lstdelone.c -o ft_lstdelone.o

ft_lsadd_back.o: ft_lsadd_back.c
	$(CC) $(CFLAGS) -c ft_lsadd_back.c -o ft_lsadd_back.o

ft_lsadd_front.o: ft_lsadd_front.c
	$(CC) $(CFLAGS) -c ft_lsadd_front.c -o ft_lsadd_front.o

ft_lstlast.o: ft_lstlast.c
	$(CC) $(CFLAGS) -c ft_lstlast.c -o ft_lstlast.o

ft_lstnew.o: ft_lstnew.c
	$(CC) $(CFLAGS) -c ft_lstnew.c -o ft_lstnew.o

ft_lstsize.o: ft_lstsize.c
	$(CC) $(CFLAGS) -c ft_lstsize.c -o ft_lstsize.o

ft_lstiter.o: ft_lstiter.c
	$(CC) $(CFLAGS) -c ft_lstiter.c -o ft_lstiter.o


all: $(NAME)

clean:
	rm -f $(OBJ)

fclean:
	rm -f $(NAME)

re: fclean
	$(MAKE) all
